---
- name: Deploy Automation Controller
  hosts: localhost
  vars:
    base_path: 'genie'
    minikube_cpu: '2'
    minikube_ram: '3g'
    genie_ip: 'localhost'
    default_credential_id: '1'
    default_project_id: '6'
    default_inventory_id: '1'
    default_template_id: '7'
    default_organization: '1'
  vars_files:
    - /genie/ansible_vars_files.json
  gather_facts: yes
  tasks:
    - name: kube config home directory setting
      shell: ln -s -f /root/.minikube /root/.kube/.minikube

    - name: Start Minikube cluster
      shell: minikube start --cpus={{ minikube_cpu }} --memory={{ minikube_ram }} --addons=ingress --install-addons=true --driver=docker --force
      tags:
        - start minikube

    - name: Minikube status check
      shell: minikube status |awk -F ' ' '/{{item.shell}}/{ print $2 }'
      register: minikube_host_stauts
      failed_when: "'Running' not in minikube_host_stauts.stdout_lines"
      with_items:
        - { shell: 'host'}
        - { shell: 'kubelet'}
        - { shell: 'apiserver'}

    - name: Genie service registration
      shell: systemctl enable genie_cluster.service

    - name: Change default namespace to awx
      shell: kubectl config set-context --current --namespace=awx

    - name: Generate SSH key
      community.crypto.openssh_keypair:
        path: /root/.ssh/id_rsa
        force: yes

    - name: Register the generated public key Mold SSH key pair
      cs_sshkeypair:
        name: "{{ AC_INSTANCE_NAME }}"
        public_key: "{{ lookup('file', '/root/.ssh/id_rsa.pub') }}"
        api_url: "{{ MOLD_API_URL }}"
        api_key: "{{ MOLD_API_KEY }}"
        api_secret: "{{ MOLD_SECRET_KEY }}"

    - name: Public key extraction
      command: "cat /root/.ssh/id_rsa.pub"
      register: id_pub
      run_once: true

    - name: Add generated public key to authenticated keys
      lineinfile:
        dest: /root/.ssh/authorized_keys
        line: "{{ id_pub.stdout }}"

    # Genie Dashboard 접속 가능할 때에 ping check 허용하여 배포 완성 시기를 사용자에게 알림
    - name: Automation Controller Egress Settings (ICMP)
      cs_firewall:
        network: "{{ AC_NETWORK_NAME }}"
        api_url: "{{ MOLD_API_URL }}"
        api_key: "{{ MOLD_API_KEY }}"
        api_secret: "{{ MOLD_SECRET_KEY }}"
        zone: "{{ MOLD_ZONE_NAME }}"
        api_timeout: 60
        icmp_code: -1
        icmp_type: -1
        protocol: icmp
        type: egress

    - name: Automation Controller Ingress Settings (ICMP)
      cs_firewall:
        ip_address: "{{ AC_PUBLIC_IP }}"
        api_url: "{{ MOLD_API_URL }}"
        api_key: "{{ MOLD_API_KEY }}"
        api_secret: "{{ MOLD_SECRET_KEY }}"
        zone: "{{ MOLD_ZONE_NAME }}"
        api_timeout: 60
        icmp_code: -1
        icmp_type: -1
        protocol: icmp

    - name: Automation Controller Ingress Settings (tcp)
      cs_firewall:
        ip_address: "{{ AC_PUBLIC_IP }}"
        api_url: "{{ MOLD_API_URL }}"
        api_key: "{{ MOLD_API_KEY }}"
        api_secret: "{{ MOLD_SECRET_KEY }}"
        zone: "{{ MOLD_ZONE_NAME }}"
        api_timeout: 60
        type: ingress
        protocol: tcp
        cidrs: 0.0.0.0/0
        start_port: 1
        end_port: 65535

    - name: Automation Controller Port forward Rule Settings
      cs_portforward:
        network: "{{ AC_NETWORK_NAME }}"
        ip_address: "{{ AC_PUBLIC_IP }}"
        vm: "{{ AC_INSTANCE_NAME }}"
        api_url: "{{ MOLD_API_URL }}"
        api_key: "{{ MOLD_API_KEY }}"
        api_secret: "{{ MOLD_SECRET_KEY }}"
        zone: "{{ MOLD_ZONE_NAME }}"
        public_port: "{{ item }}"
        private_port: "{{ item }}"
        api_timeout: 70
      with_items:
        - 80
        - 22
        - 5432
        - 8001

    - name: Genie Dashboard waiting for response
      shell: curl -o /dev/null -s -w "%{http_code}\n" http://{{ genie_ip }}:80
      register: genie_return_code
      until: genie_return_code.stdout == "200"
      retries: 50

    ##### AWX 셋팅
    - name: Extract AWX initial administrator password
      shell: kubectl get -n awx secret awx-admin-password -o jsonpath="{.data.password}" | base64 --decode
      register: admin_password

    - name: Job settings - Global variable setting
      awx.awx.settings:
        settings:
          AWX_TASK_ENV:
            MOLD_API_URL: "{{ MOLD_API_URL }}"
            MOLD_API_KEY: "{{ MOLD_API_KEY }}"
            MOLD_SECRET_KEY: "{{ MOLD_SECRET_KEY }}"
            MOLD_ZONE_ID: "{{ MOLD_ZONE_ID }}"
            MOLD_ZONE_NAME: "{{ MOLD_ZONE_NAME }}"
            MOLD_SSH_KEYPAIR: "{{ AC_INSTANCE_NAME }}"
            AC_ID: "{{ AC_ID }}"
            AC_INSTANCE_NAME: "{{ AC_INSTANCE_NAME }}"
            AC_NETWORK_NAME: "{{ AC_NETWORK_NAME }}"
            AC_NETWORK_ADDRESS: "{{ ansible_default_ipv4.address }}"
            MOLD_DEFAULT_URL: "{{ MOLD_DEFAULT_URL }}"
            MOLD_DEFAULT_PORT: "{{ MOLD_DEFAULT_PORT }}"
            MOLD_DEFAULT_PROTOCOL: "{{ MOLD_DEFAULT_PROTOCOL[:-3] }}"
        controller_host: "http://{{ genie_ip }}:80"
        controller_username: admin
        controller_password: "{{ admin_password.stdout }}"

    - name: Delete default job template
      uri:
        url: http://{{ genie_ip }}:80/api/v2/job_templates/{{ default_template_id }}/
        method: DELETE
        body_format: json
        user: admin
        password: "{{ admin_password.stdout }}"
        force_basic_auth: yes
        body:
          {
          }
        status_code: 204

    - name: Change default credential name
      uri:
        url: http://{{ genie_ip }}:80/api/v2/credentials/{{ default_credential_id }}/
        method: PATCH
        body_format: json
        user: admin
        password: "{{ admin_password.stdout }}"
        force_basic_auth: yes
        body:
          {
            "name": "Default Credential",
            "description": "Genie EE에 SSH 접근을 위한 인증 정보입니다."
          }
        status_code: 200

    - name: Delete default project
      uri:
        url: http://{{ genie_ip }}:80/api/v2/projects/{{ default_project_id }}/
        method: DELETE
        body_format: json
        user: admin
        password: "{{ admin_password.stdout }}"
        force_basic_auth: yes
        status_code: 204
      ignore_errors: yes

    - name: Rename Default Inventory to Genie Inventory
      uri:
        url: http://{{ genie_ip }}:80/api/v2/inventories/{{ default_inventory_id }}/
        method: PATCH
        body_format: json
        user: admin
        password: "{{ admin_password.stdout }}"
        force_basic_auth: yes
        body:
          {
            "name": "Genie Inventory",
            "organization": "{{ default_organization }}",
            "description": "Genie 자동화 서비스에서 사용하는 인벤토리 정보입니다."
          }
        status_code: 200

    - name: Change Cleanup Job Schedule settings
      awx.awx.schedule:
        name: Cleanup Job Schedule
        state: present
        unified_job_template: Cleanup Job Details
        rrule: "DTSTART;TZID=Asia/Seoul:20220101T120000 RRULE:FREQ=DAILY;INTERVAL=1"
        extra_data:
          {
            "days": "7"
          }
        controller_host: "http://{{ genie_ip }}:80"
        controller_username: admin
        controller_password: "{{ admin_password.stdout }}"

    - name: Create Automation Controller Credentials
      awx.awx.credential:
        name: Automation Controller Credential
        description: 오토메이션 컨트롤러에 SSH 접속을 위한 인증 정보입니다.
        organization: Default
        credential_type: Machine
        state: present
        inputs:
          username: root
          ssh_key_data: "{{ lookup('file', '/root/.ssh/id_rsa') }}"
        controller_host: "http://{{ genie_ip }}:80"
        controller_username: admin
        controller_password: "{{ admin_password.stdout }}"

    - name: Add host (automation controller) to genie_inventory (default inventory)
      uri:
        url: http://{{ genie_ip }}:80/api/v2/inventories/{{ default_inventory_id }}/hosts/
        method: POST
        body_format: json
        user: admin
        password: "{{ admin_password.stdout }}"
        force_basic_auth: yes
        body:
          {
            "name": "{{ ansible_default_ipv4.address }}",
            "description": "오토메이션 컨트롤러의 IP입니다."
          }
        status_code: 201

    - name: Add group (genie_vm) to genie_inventory (default inventory)
      uri:
        url: http://{{ genie_ip }}:80/api/v2/inventories/{{ default_inventory_id }}/groups/
        method: POST
        body_format: json
        user: admin
        password: "{{ admin_password.stdout }}"
        force_basic_auth: yes
        body:
          {
            "name": "genie_vm",
          }
        status_code: 201
      register: group

    - name: Add automation controller host to genie_vm group in genie_inventory (default inventory)
      uri:
        url: http://{{ genie_ip }}:80/api/v2/groups/{{ group.json.id }}/hosts/
        method: POST
        body_format: json
        user: admin
        password: "{{ admin_password.stdout }}"
        force_basic_auth: yes
        body:
          {
            "name": "{{ ansible_default_ipv4.address }}",
            "inventory": "{{ default_inventory_id }}"
          }
        status_code: 204

    # - name: Create a Genie remote repository project
    #   uri:
    #     url: http://{{ genie_ip }}:80/api/v2/projects/
    #     method: POST
    #     body_format: json
    #     user: admin
    #     password: "{{ admin_password.stdout }}"
    #     force_basic_auth: yes
    #     body:
    #       {
    #         "name": "remote_archive_project",
    #         "scm_type": "archive",
    #         "scm_url": "http://{{ MOLD_DEFAULT_URL }}:7000/nextcloud.zip",
    #         "scm_delete_on_update": "true"
    #       }
    #     status_code: 201

    - name: Create a Genie Git project
      awx.awx.project:
        name: Genie Git Project
        description: ABLECLOUD에서 제공하는 자동화 서비스 플레이북의 Git 저장소 입니다.
        default_environment: AWX EE (genie_latest)
        organization: "Default"
        scm_type: git
        scm_url: https://github.com/ablecloud-team/ablestack-genie.git
        scm_branch: master
        scm_update_on_launch: no
        state: present
        controller_host: "http://{{ genie_ip }}:80"
        controller_username: admin
        controller_password: "{{ admin_password.stdout }}"

    - name: Create a template that calls the Genie template list
      awx.awx.job_template:
        name: Genie 템플릿 리스트 불러오기 및 업데이트
        description: Genie 서비스를 이용하기 위해 ABLESTACK에서 제공하는 자동화 템플릿을 불러옵니다. 다시 실행하게 되면 템플릿에 변경사항이 있을 경우 업데이트됩니다.
        job_type: "run"
        inventory: Genie Inventory
        project: Genie Git Project
        playbook: playbook/template/template_deploy.yml
        credentials:
          - "Automation Controller Credential"
        state: "present"
        controller_host: "http://{{ genie_ip }}:80"
        controller_username: admin
        controller_password: "{{ admin_password.stdout }}"
